// ============================================================
// AEROSCOUT — API CONFIGURATION
// Central registry for all backend endpoints & WebSocket URLs
// Edit .env (local) or set environment variables (production)
// ============================================================

const BASE_URL    = import.meta.env.VITE_API_BASE_URL    || 'http://localhost:8000';
const WS_BASE_URL = import.meta.env.VITE_WS_BASE_URL     || 'ws://localhost:8000';
const MAP_TILES   = import.meta.env.VITE_MAP_TILES_URL   || 'https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png';

// ── DRONE TELEMETRY ────────────────────────────────────────
// Input : GET polling or WebSocket subscription
// Output: { id, lat, lon, altitude, speed, battery, signal, heading, status, gps, missionZone }
export const DRONE_ENDPOINTS = {
  /** REST: get current state of all drones */
  getAll:     `${BASE_URL}/api/v1/drones`,

  /** REST: get single drone by ID */
  getById:    (droneId) => `${BASE_URL}/api/v1/drones/${droneId}`,

  /** WebSocket: real-time telemetry stream for all drones
   *  Message format: { type: 'telemetry', data: Drone[] }
   */
  telemetryWS: `${WS_BASE_URL}/ws/drones/telemetry`,

  /** POST: assign drone to a zone
   *  Body: { droneId: string, zone: string }
   *  Response: { success: boolean, message: string }
   */
  assignZone: `${BASE_URL}/api/v1/drones/assign-zone`,

  /** POST: update drone mission command
   *  Body: { droneId: string, command: 'pause'|'resume'|'rtb'|'emergency' }
   *  Response: { success: boolean, ack: string }
   */
  command:    `${BASE_URL}/api/v1/drones/command`,
};

// ── AI DETECTIONS ──────────────────────────────────────────
// Input : WebSocket stream from on-device YOLO11m-seg inference
// Output: { id, type, label, emoji, priority, confidence, lat, lon, droneId, timestamp, coordsStr }
export const DETECTION_ENDPOINTS = {
  /** REST: get all detections for current mission */
  getAll:     `${BASE_URL}/api/v1/detections`,

  /** REST: get detections filtered by type
   *  Query params: ?type=survivor|fire|flood|debris|landslide|structural|electrical|chemical
   *  Query params: ?droneId=ALPHA-1&since=2026-09-20T00:00:00Z&limit=50
   */
  getFiltered: `${BASE_URL}/api/v1/detections/filter`,

  /** REST: get single detection by ID */
  getById:    (detectionId) => `${BASE_URL}/api/v1/detections/${detectionId}`,

  /** WebSocket: real-time detection stream from drone AI inference
   *  Message format: { type: 'detection', data: Detection }
   *  Emitted every time YOLO11m-seg flags a new object
   */
  liveWS:     `${WS_BASE_URL}/ws/detections/live`,

  /** POST: manually submit a detection (operator override)
   *  Body: { type, label, confidence, lat, lon, droneId }
   *  Response: { id, timestamp, ...detection }
   */
  submit:     `${BASE_URL}/api/v1/detections`,
};

// ── ALERTS ─────────────────────────────────────────────────
// Input : auto-generated by backend from high-priority detections
// Output: { id, detectionId, type, priority, title, description, lat, lon, droneId, status, countdown }
export const ALERT_ENDPOINTS = {
  /** REST: get all alerts for current mission */
  getAll:     `${BASE_URL}/api/v1/alerts`,

  /** REST: get only open (unresolved) alerts */
  getOpen:    `${BASE_URL}/api/v1/alerts?status=open`,

  /** WebSocket: real-time alert stream
   *  Message format: { type: 'alert', data: Alert }
   */
  liveWS:     `${WS_BASE_URL}/ws/alerts/live`,

  /** PATCH: dispatch a rescue team to an alert
   *  Body: { teamId?: string, notes?: string }
   *  Response: { id, status: 'dispatched', dispatchedAt, teamId }
   */
  dispatch:   (alertId) => `${BASE_URL}/api/v1/alerts/${alertId}/dispatch`,

  /** PATCH: resolve/close an alert
   *  Body: { resolution: string }
   *  Response: { id, status: 'resolved', resolvedAt }
   */
  resolve:    (alertId) => `${BASE_URL}/api/v1/alerts/${alertId}/resolve`,

  /** DELETE: dismiss an alert
   *  Response: { success: boolean }
   */
  dismiss:    (alertId) => `${BASE_URL}/api/v1/alerts/${alertId}`,
};

// ── MISSION CONTROL ────────────────────────────────────────
// Input : operator commands from the command center UI
// Output: mission status and acknowledgements
export const MISSION_ENDPOINTS = {
  /** GET: current mission status
   *  Response: { id, name, status, startTime, scenario, location, drones[] }
   */
  status:     `${BASE_URL}/api/v1/mission/status`,

  /** POST: pause all drone operations
   *  Response: { success: boolean, status: 'paused' }
   */
  pause:      `${BASE_URL}/api/v1/mission/pause`,

  /** POST: resume paused mission
   *  Response: { success: boolean, status: 'active' }
   */
  resume:     `${BASE_URL}/api/v1/mission/resume`,

  /** POST: return all drones to base
   *  Response: { success: boolean, eta: number (seconds) }
   */
  returnToBase: `${BASE_URL}/api/v1/mission/rtb`,

  /** POST: emergency recall — highest priority RTB
   *  Response: { success: boolean, overrideActive: boolean }
   */
  emergency:  `${BASE_URL}/api/v1/mission/emergency`,

  /** GET: download situational report (PDF/JSON)
   *  Query: ?format=pdf|json
   *  Response: file download or JSON report
   */
  report:     `${BASE_URL}/api/v1/mission/report`,
};

// ── CAMERA FEEDS ───────────────────────────────────────────
// Input : drone ID and camera type
// Output: HLS/RTSP video stream URL or MJPEG snapshot
export const CAMERA_ENDPOINTS = {
  /** GET: HLS video stream (m3u8) for a drone camera
   *  Params: droneId, mode: 'rgb'|'thermal'
   *  Response: redirect to HLS .m3u8 stream
   */
  hlsStream:  (droneId, mode = 'rgb') =>
    `${BASE_URL}/api/v1/camera/${droneId}/stream?mode=${mode}`,

  /** GET: MJPEG snapshot frame (for canvas rendering)
   *  Response: image/jpeg
   */
  snapshot:   (droneId, mode = 'rgb') =>
    `${BASE_URL}/api/v1/camera/${droneId}/snapshot?mode=${mode}`,

  /** WebSocket: raw frame stream with YOLO bbox overlay data
   *  Message format: { frame: base64, bboxes: BBox[], timestamp: string }
   */
  frameWS:    (droneId) => `${WS_BASE_URL}/ws/camera/${droneId}/frames`,
};

// ── GEO / MAP ──────────────────────────────────────────────
// Map tiles and geo-data endpoints
export const GEO_ENDPOINTS = {
  /** Leaflet tile URL template */
  mapTiles:   MAP_TILES,

  /** GET: geo-tagged survivor and hazard markers for current mission
   *  Response: GeoJSON FeatureCollection
   */
  geoJSON:    `${BASE_URL}/api/v1/geo/markers`,

  /** GET: drone flight paths as GeoJSON LineStrings */
  flightPaths:`${BASE_URL}/api/v1/geo/paths`,

  /** GET: safe access routes as GeoJSON */
  safeRoutes: `${BASE_URL}/api/v1/geo/routes`,

  /** GET: hazard zone polygons as GeoJSON */
  hazardZones:`${BASE_URL}/api/v1/geo/hazard-zones`,
};

// ── SENSOR FUSION / EDGE AI ───────────────────────────────
// On-device model inference status and results
export const AI_ENDPOINTS = {
  /** GET: YOLO11m inference stats per drone
   *  Response: { droneId, model, fps, latencyMs, device, isOnline }
   */
  inferenceStats: (droneId) => `${BASE_URL}/api/v1/ai/${droneId}/stats`,

  /** POST: update YOLO model confidence threshold
   *  Body: { droneId: string, threshold: number (0–1) }
   *  Response: { success: boolean, newThreshold: number }
   */
  setThreshold: `${BASE_URL}/api/v1/ai/threshold`,

  /** GET: model health across all drones */
  health:       `${BASE_URL}/api/v1/ai/health`,
};

// ── WEBSOCKET MANAGER ─────────────────────────────────────
// Helper to create & manage WebSocket connections
export class WSManager {
  constructor(url, onMessage, onOpen, onClose, onError) {
    this.url = url;
    this.onMessage = onMessage;
    this.onOpen    = onOpen;
    this.onClose   = onClose;
    this.onError   = onError;
    this.ws        = null;
    this.retries   = 0;
    this.maxRetries = 5;
    this.retryDelay = 3000;
  }

  connect() {
    this.ws = new WebSocket(this.url);
    this.ws.onopen    = () => { this.retries = 0; this.onOpen?.(); };
    this.ws.onmessage = (e) => this.onMessage?.(JSON.parse(e.data));
    this.ws.onclose   = () => { this.onClose?.(); this._retry(); };
    this.ws.onerror   = (e) => this.onError?.(e);
    return this;
  }

  _retry() {
    if (this.retries < this.maxRetries) {
      this.retries++;
      console.warn(`[WSManager] Reconnecting (${this.retries}/${this.maxRetries})…`);
      setTimeout(() => this.connect(), this.retryDelay * this.retries);
    }
  }

  send(data) { this.ws?.readyState === WebSocket.OPEN && this.ws.send(JSON.stringify(data)); }
  close()    { this.ws?.close(); }
}

// ── FETCH HELPER ──────────────────────────────────────────
// Typed API helper with auth header support
export async function apiFetch(url, options = {}) {
  const token = import.meta.env.VITE_API_TOKEN;
  const headers = {
    'Content-Type': 'application/json',
    ...(token ? { Authorization: `Bearer ${token}` } : {}),
    ...options.headers,
  };

  const res = await fetch(url, { ...options, headers });
  if (!res.ok) {
    const err = await res.json().catch(() => ({ message: res.statusText }));
    throw new Error(err.message || `API error ${res.status}`);
  }
  return res.json();
}

// ── EXPORT ALL ────────────────────────────────────────────
export const API = {
  drones:    DRONE_ENDPOINTS,
  detections: DETECTION_ENDPOINTS,
  alerts:    ALERT_ENDPOINTS,
  mission:   MISSION_ENDPOINTS,
  camera:    CAMERA_ENDPOINTS,
  geo:       GEO_ENDPOINTS,
  ai:        AI_ENDPOINTS,
};

export default API;
